spring:
  application:
    name: prometheus-grafana-demo

management:
  endpoints:
    web.exposure.include: '*'

# created http_server_requests_seconds_bucket metrics

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http.server.requests: true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: trace