global:
  scrape_interval:   15s # By default, scrape targets every 15 seconds.

scrape_configs:
- job_name:       'prometheus-grafana-demo'

  # Override the global default and scrape targets from this job every 10 seconds.
  scrape_interval: 10s
  metrics_path: '/actuator/prometheus'

  # scheme defaults to 'http'
  static_configs:
  - targets: ['192.168.0.159:8080']
    labels:
      application: 'prometheus-grafana-demo'
